export const ICONS = {
  travel: "cuida:calendar-outline",
  meals: "material-symbols-light:fork-spoon",
  itinerary: "mingcute:location-fill",
  accommodation: "tdesign:fog-night",
  arrow: "solar:alt-arrow-up-line-duotone",
  check: "mingcute:check-fill",
  arrow2: "ri:arrow-up-line",
  info: "akar-icons:info",
  close: "mdi:close",
  arrival: "carbon:arrival",
  departure: "carbon:departure",
  welcome: "fluent:people-queue-20-regular",
  deposit: "carbon:wallet",
  depositProtection: "material-symbols:airplane-ticket-outline",
  freeBookingChanges: "fluent:calendar-star-24-regular",
  dot: "material-symbols:circle",
  dotVisited: "oui:dot",
  dotOne: "emojione-monotone:digit-one",

  plane: "ri:plane-line",
  cruise: "icon-park-outline:cruise",
  train: "ic:sharp-train",
};
